# Use the official Python image as the base image
FROM python:3.11-slim-buster

# Set the working directory inside the container
WORKDIR /ran-guardian

# Install poetry
RUN pip install --upgrade pip && \
    pip install poetry

# Copy the poetry.lock and pyproject.toml files first (for caching)
COPY poetry.lock pyproject.toml ./

# Install project dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

# Copy the rest of the application code
COPY . .

# Copy the .env file into the container
COPY .env .

# Expose the ports
EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "app.main:app", "--port", "8000", "--host", "0.0.0.0"]
